name: github pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build and deploy GitHub Pages
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Caching yarn dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          yarn deploy
          echo 🤘 Deploy to GitHub Pages completed.