name: github pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build and deploy GitHub Pages
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Caching yarn dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          cd ./dist
          git init
          git config --local user.name "Irene Wang"
          git config --local user.email "lohas1107@gmail.com"
          git remote add origin https://${{secrets.DEPLOY_GITHUB_PAGE_SECRET}}@github.com/lohas1107/hello-web-layout.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy to GitHub Pages by GitHub Actions"
          git push origin gh-pages -f
          echo 🤘 Deploy to GitHub Pages completed.